export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Products } from './Products';
export { default as Checkout } from './Checkout';
export { default as Orders } from './Orders';
export { default as OrderDetails } from './OrderDetails';
export { default as OrdersSeller } from './OrdersSeller';
export { default as OrderDetailsSeller } from './OrderDetailsSeller';
export { default as Management } from './Management';
